### PR TITLE
update benchmarked to latest and related changes, add one more benchmark

### PR DESCRIPTION
**Pull request by tunnckoCore**
ref #4 

If that added benchmark case is okey, we can make it current?

### CODE REVIEW

**Comment by jonschlinkert** [comment]
> we can make it current?

make what current?

**Comment by jonschlinkert** [comment]
If you mean, remove `kind-of` and use the code in your pr, no. Why would we create more complexity in this module when that code is already well unit-tested and optimized in kind-of? kind-of is a very small and optimized library. Any extremely small optimizations we might by moving code from kind-of to this library are outweighed by the benefits of the module pattern in this case. Normally I might consider it more, but given how much both modules are downloaded, I'm not inclined to make gratuitous changes.

**Comment by tunnckoCore** [comment]
> make what current?

This bench case. It is faster than current and reduces the huge size address in #4

**Comment by jonschlinkert** [comment]
Please read the updated message on https://github.com/jonschlinkert/is-number/issues/4. Clearly no one is comprehending that _**the size issue was resolved 1 1/2 years ago**_. I'm not sure how to make this more obvious.

**Pull request closed without merging**
